# Generated by Django 5.0.4 on 2024-05-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre_completo'),
        ),
    ]
