# Generated by Django 5.0.4 on 2024-05-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='image',
            new_name='imagen',
        ),
    ]
