# Generated by Django 5.0.4 on 2024-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('shortName', models.CharField(max_length=50, verbose_name='nombre corto')),
                ('activo', models.BooleanField(default=False, verbose_name='anulado')),
            ],
        ),
    ]
