# Generated by Django 5.0.4 on 2024-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='shortName',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='nombre corto'),
        ),
    ]
