# Generated by Django 5.0.4 on 2024-04-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_alter_departamento_name_alter_departamento_shortname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mi prueba', 'verbose_name_plural': 'Area de prueba'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'shortName')},
        ),
    ]
